### ISSUE TITLE
why its happening help plzzzz....

### ISSUE THREAD

**Issue by mamun626** [dubbadhar/whatsappBomber#2]
Traceback (most recent call last):
  File "bomber.py", line 150, in <module>
    app_method_1()
  File "bomber.py", line 131, in app_method_1
    driver = webdriver.Firefox()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)

**Comment by dubbadhar** [comment]
sorry, project is abandoned
